name: Docker Image CI

on:
  # Run only when a new release has been created
  workflow_run:
    workflows: ["goreleaser"]
    types:
      - completed
  workflow_dispatch:

env:
  REGISTRY: locotech
  IMAGE_NAME: pcc-reporter

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get latest release tag'
        id: release_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Get release tag without prefix
        id: release_tag_no_prefix
        run: |
          version=${{steps.release_tag.outputs.tag}}
          echo "Version input ${version}"
          echo "Version output ${version:1}"
          echo "tag_no_prefix=${version:1}" >> "$GITHUB_OUTPUT"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # needed so we can split the build and push to separate steps
          # for Prisma Cloud scanning
          driver: docker
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{steps.release_tag.outputs.tag}},priority=950
            type=semver,pattern={{major}}.{{minor}},value=${{steps.release_tag.outputs.tag}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            RELEASE_VERSION=${{steps.release_tag_no_prefix.outputs.tag_no_prefix}}

      - name: Look up images
        run: docker image ls

      - name: Prisma Cloud image scan
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1
        with:
          pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
          pcc_user: ${{ secrets.PCC_USER }}
          pcc_pass: ${{ secrets.PCC_PASS }}
          image_name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}

      # push the image manually
      - name: Push image
        run: docker push --all-tags ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
