name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      ## this will contain a matrix of all of the architecture
      ## combinations we wish to build
      matrix:
        goos: [darwin, linux, windows]
        goarch: [386, amd64]
        exclude:
          - goos: darwin
            goarch: 386
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./build/pcc-reporter-${{ matrix.goos }}-${{ matrix.goarch }} -v -ldflags="-s -w" ./main.go

      - name: Rename windows exec
        if: matrix.goos == 'windows'
        run: for x in ./build/pcc-reporter-windows-*; do mv $x $x.exe; done

      - name: Bin
        uses: actions/upload-artifact@v3
        with:
          name: pcc-reporter
          path: ./build/
